### ISSUE TITLE
Adoptify org

### ISSUE THREAD

**Issue by YoussefBO** [ArmandoLun/adoptifydeploy#1]
Hi @ArmandoLun,

I'd like to use the org name "adoptify". If you're not using it anymore, do you mind releasing it or transferring the ownership to me please?

Sorry for the bother and all the best to you!

**Comment by ArmandoLun** [comment]
Sure, my job was just a study project. do you want me to delete my
repository from github?

**Comment by YoussefBO** [comment]
Yes please, if you could delete the adoptify organisation (not a repo) that'd be great. Thank you!!

**Comment by ArmandoLun** [comment]
[image: image.png]
Done! You are welcome.

**Comment by YoussefBO** [comment]
Thank you very much!
